CREATE TABLE FAILSAFE_TASK (
    ID VARCHAR2(36) NOT NULL,
    PARAMETER VARCHAR2(200),
    NAME VARCHAR2(200) NOT NULL,
    PLANNED_EXECUTION_TIME TIMESTAMP,
    LOCK_TIME TIMESTAMP,
    FAILED NUMBER(1) DEFAULT 0,
    FAIL_TIME TIMESTAMP,
    EXCEPTION_MESSAGE VARCHAR2(1000),
    STACK_TRACE CLOB,
    VERSION NUMBER(4) DEFAULT 0,
    CREATED_DATE TIMESTAMP,
    PRIMARY KEY (ID,NAME)
);