CREATE TABLE PERSISTENT_TASK (
    ID varchar2(36) NOT NULL,
    PARAMETER varchar2(200),
    NAME varchar2(200) NOT NULL,
    START_TIME TIMESTAMP,
    FAILED NUMBER(1) DEFAULT 0,
    EXCEPTION_MESSAGE varchar2(1000),
    STACK_TRACE CLOB,
    VERSION NUMBER(4) DEFAULT 0,
    LAST_MODIFIED_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);