CREATE TABLE TASK_INSTANCE (
    ID varchar2(36) NOT NULL,
    PARAMETER varchar2(200),
    NAME varchar2(200) NOT NULL,
    START_TIME TIMESTAMP,
    FAILED NUMBER(1) DEFAULT 0,
    VERSION NUMBER(4) DEFAULT 0,
    LAST_MODIFIED_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE TASK_INCIDENT (
    ID varchar2(36) NOT NULL,
    TASK_ID varchar2(36) NOT NULL,
    MESSAGE varchar2(1000) NOT NULL,
    STACKTRACE CLOB,
    LAST_MODIFIED_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);